[package]
name = "docker-test"
version = "0.1.0"
authors = ["Steve Smith <tarkasteve@gmail.com>"]
license = "MPL-2.0"
edition = "2021"

[dependencies]
anyhow = "1.0.52"
camino = "1.0.7"
cfg-if = "1.0.0"
libc = "0.2.112"
