[package]
name = "docker-test"
version = "0.1.0"
authors = ["Steve Smith <tarkasteve@gmail.com>"]
license = "MPL-2.0"
edition = "2021"

[dependencies]
anyhow = "1.0.52"
camino = "1.0.7"
cfg-if = "1.0.0"
libc = "0.2.112"
log = "0.4.14"
simplelog = "0.11.2"
structopt = "0.3.25"
thiserror = "1.0.30"
